# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/book/service_container.html
parameters:
#    parameter_name: value

services:
#    service_name:
#        class: AppBundle\Directory\ClassName
#        arguments: ["@another_service_name", "plain_value", "%parameter_name%"]
    service.slug:
        class: AppBundle\Service\Slug
        arguments: [@doctrine.orm.entity_manager]
    service.city:
        class: AppBundle\Service\City
        arguments: [@doctrine.orm.entity_manager]
    service.restaurant:
        class: AppBundle\Service\Restaurant
        arguments: [@doctrine.orm.entity_manager]
    service.pizza:
        class: AppBundle\Service\Pizza
        arguments: [@doctrine.orm.entity_manager, @service.slug]
    app.twig_extension:
        class: AppBundle\Twig\PizzaExtension
        public: false
        tags:
            - { name: twig.extension }
